BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "kho" (
	"Plant"	REAL,
	"Material"	REAL,
	"Storage Location"	REAL,
	"Material Description"	TEXT,
	"ID Cuộn Bó"	REAL,
	"Vị trí"	TEXT,
	"Khối lượng"	REAL,
	"Nhóm"	TEXT,
	"Ca"	TEXT,
	"Ngày sản xuất"	TEXT,
	"SO Mapping"	REAL,
	"SO Item Ma"	REAL,
	"Customer N"	TEXT,
	"Batch"	REAL,
	"Order"	REAL,
	"Loại thép"	TEXT,
	"Chiều dài"	REAL,
	"Đường kính"	REAL,
	"Mác thép"	TEXT,
	"Tiêu chuẩn"	TEXT,
	"Đơn vị tính"	TEXT,
	"Số lượng"	REAL,
	"Lô Phôi"	TEXT,
	"Phân xưởng"	REAL,
	"Nhà máy"	REAL,
	"Trạm cân"	REAL,
	"Cơ lý"	REAL,
	"Số lượng in"	REAL,
	"Nhập tay"	TEXT,
	"SampleID"	REAL,
	"Customer M"	REAL,
	"Tp loại 2"	TEXT,
	"snapshot_ts"	TEXT,
	"status"	TEXT,
	PRIMARY KEY("ID Cuộn Bó")
);
CREATE TABLE IF NOT EXISTS "kho_removed" (
	"Plant"	REAL,
	"Material"	REAL,
	"Storage Location"	REAL,
	"Material Description"	TEXT,
	"ID Cuộn Bó"	REAL,
	"Vị trí"	TEXT,
	"Khối lượng"	REAL,
	"Nhóm"	TEXT,
	"Ca"	TEXT,
	"Ngày sản xuất"	TEXT,
	"SO Mapping"	REAL,
	"SO Item Ma"	REAL,
	"Customer N"	TEXT,
	"Batch"	REAL,
	"Order"	REAL,
	"Loại thép"	TEXT,
	"Chiều dài"	REAL,
	"Đường kính"	REAL,
	"Mác thép"	TEXT,
	"Tiêu chuẩn"	TEXT,
	"Đơn vị tính"	TEXT,
	"Số lượng"	REAL,
	"Lô Phôi"	TEXT,
	"Phân xưởng"	REAL,
	"Nhà máy"	REAL,
	"Trạm cân"	REAL,
	"Cơ lý"	REAL,
	"Số lượng in"	REAL,
	"Nhập tay"	TEXT,
	"SampleID"	REAL,
	"Customer M"	REAL,
	"Tp loại 2"	TEXT,
	"snapshot_ts"	TEXT,
	"status"	TEXT
);
CREATE TABLE IF NOT EXISTS "lichtau" (
	"STT"	REAL,
	"SỐ LỆNH TÁCH"	TEXT,
	"TÀU/PHƯƠNG TIỆN VẬN TẢI"	TEXT,
	"KHỐI LƯỢNG TỔNG TÀU"	REAL,
	"ETA DUNG QUẤT"	TEXT,
	"ĐẠI LÝ"	TEXT,
	"ETB DUNG QUẤT"	TEXT,
	"NGÀY DK DUYỆT SO"	TEXT,
	"Cảng xếp"	TEXT,
	"CẢNG ĐẾN"	TEXT,
	"LỆNH XUẤT HÀNG - KẾ HOẠCH DUYỆT (SỐ LỆNH ĐẦY ĐỦ - SỐ XNĐH - KL TỔNG ĐƠN - LSD) (MỖI LỆNH 1 DÒNG)"	TEXT,
	"KHỐI LƯỢNG HÀNG XUẤT LÊN TÀU"	REAL,
	"SẢN XUẤT (HRC 1/2-TÌNH TRẠNG)"	TEXT,
	"C.W MAX TÀU NHẬN ĐƯỢC"	REAL,
	"GHI CHÚ"	TEXT,
	"NHỊP"	INTEGER,
	"TÌNH TRẠNG"	REAL,
	"SO"	REAL,
	"TỔNG ĐÃ MAP"	REAL,
	"ĐÃ XUẤT"	TEXT,
	"CÒN LẠI"	TEXT
);
CREATE TABLE IF NOT EXISTS "lsx" (
	"Order"	REAL,
	"KHÁCH HÀNG"	TEXT,
	"Tổng yêu cầu"	REAL,
	"SL trung bình/ngày"	REAL,
	"lsx_id"	TEXT
);
CREATE TABLE IF NOT EXISTS "report" (
	"Order"	REAL,
	"KHÁCH HÀNG"	TEXT,
	"Tổng yêu cầu"	REAL,
	"SL trung bình/ngày"	REAL,
	"lsx_id"	TEXT,
	"Ngày"	TIMESTAMP,
	"Sản lượng thực tế"	REAL,
	"Tổng sản lượng thực tế"	REAL,
	"Trong_khoang_LSX"	INTEGER,
	"Trạng thái"	TEXT
);
CREATE TABLE IF NOT EXISTS "sanluong" (
	"Material Description"	TEXT,
	"Nhóm"	TEXT,
	"ID Cuộn Bó"	REAL,
	"Khối lượng"	REAL,
	"Vị trí"	TEXT,
	"Lô Phôi XK"	TEXT,
	"Ngày sản xuất"	TEXT,
	"Batch"	REAL,
	"ID Ref"	REAL,
	"Order"	REAL,
	"Tp loại 2"	INTEGER,
	"QLCL"	INTEGER,
	"Material"	REAL,
	"Ca"	TEXT,
	"Đã xóa"	TEXT,
	"Đã nhập kho"	TEXT,
	"Lô phôi"	TEXT,
	"Đường kính"	REAL,
	"Mác thép"	TEXT,
	"Đã chuyển"	TEXT,
	"Đã xuất kho"	TEXT,
	"Chuyển loại"	TEXT,
	"Lỗi đơn trọng dương - L*(+)"	INTEGER,
	"Đã chuyển kho bán hàng"	TEXT
);
CREATE TABLE IF NOT EXISTS "sanluongthucte" (
	"Order"	REAL,
	"Ngày"	TIMESTAMP,
	"Sản lượng thực tế"	REAL
);
CREATE TABLE IF NOT EXISTS "sanluongthuctetong" (
	"Order"	REAL,
	"Tổng sản lượng thực tế"	REAL
);
CREATE TABLE IF NOT EXISTS "so" (
	"PO."	TEXT,
	"Sales Document"	INTEGER,
	"Customer"	TEXT,
	"Material"	INTEGER,
	"Item Description"	TEXT,
	"Quantity (KG)"	REAL,
	"Quantity (S.U)"	REAL,
	"Deli.Priority"	INTEGER,
	"Shipped Quantity (S.U)"	REAL,
	"Shipped Quantity (KG)"	REAL,
	"Delivery Status Description"	TEXT,
	"Cus.PO."	REAL,
	"Factory"	TEXT,
	"Ship to party"	TEXT,
	"Customer Number"	INTEGER,
	"Billed Qty"	REAL,
	"Billed Qty (KG)"	REAL,
	"Created by"	TEXT,
	"Sales Unit"	TEXT,
	"Sales Document Item"	INTEGER,
	"Schedule Delivery Date"	REAL,
	"Basic data text"	TEXT,
	"Reqd Deliv Date"	TEXT,
	"SL cần xuất"	REAL,
	"Ghi chú GH (LXH)"	REAL,
	"Ghi chu (YCSX)"	REAL,
	"Batch"	REAL,
	"Size"	TEXT,
	"Status"	TEXT,
	"snapshot_ts"	TEXT,
	"status1"	TEXT,
	PRIMARY KEY("Sales Document","Material","Sales Document Item")
);
CREATE TABLE IF NOT EXISTS "so_removed" (
	"PO."	TEXT,
	"Sales Document"	INTEGER,
	"Customer"	TEXT,
	"Material"	INTEGER,
	"Item Description"	TEXT,
	"Quantity (KG)"	REAL,
	"Quantity (S.U)"	REAL,
	"Deli.Priority"	INTEGER,
	"Shipped Quantity (S.U)"	REAL,
	"Shipped Quantity (KG)"	REAL,
	"Delivery Status Description"	TEXT,
	"Cus.PO."	REAL,
	"Factory"	TEXT,
	"Ship to party"	TEXT,
	"Customer Number"	INTEGER,
	"Billed Qty"	REAL,
	"Billed Qty (KG)"	REAL,
	"Created by"	TEXT,
	"Sales Unit"	TEXT,
	"Sales Document Item"	INTEGER,
	"Schedule Delivery Date"	REAL,
	"Basic data text"	TEXT,
	"Reqd Deliv Date"	TEXT,
	"SL cần xuất"	REAL,
	"Ghi chú GH (LXH)"	REAL,
	"Ghi chu (YCSX)"	REAL,
	"Batch"	REAL,
	"Size"	TEXT,
	"Status"	TEXT,
	"snapshot_ts"	TEXT,
	"status1"	TEXT
);
CREATE TABLE IF NOT EXISTS "ton_kho" (
	"index"	REAL,
	"Order"	INTEGER,
	"Material"	TEXT,
	"Material Description_x"	TEXT,
	"Tồn kho chưa Mapping SO"	INTEGER,
	"Tồn kho Mapping SO"	INTEGER,
	"Tổng tồn kho"	INTEGER,
	"Tổng Loại 1"	INTEGER,
	"Tổng Loại 2"	INTEGER,
	"Số lượng chờ nhập kho"	INTEGER,
	"SO Mapping"	INTEGER,
	"Material Description_y"	TEXT,
	"Customer N"	TEXT,
	"SL Mapping kho"	INTEGER,
	"Shipped Quantity (KG)"	INTEGER,
	"Quantity (KG)"	INTEGER,
	"Process"	INTEGER,
	"Material Description"	TEXT,
	"lsx_id"	TEXT
);
COMMIT;
