

/*==============================================================*/
/* Bảng kho                                                    */
/*==============================================================*/
CREATE TABLE dbo.kho (
    [Plant] FLOAT,
    [Material] FLOAT,
    [Storage Location] FLOAT,
    [Material Description] NVARCHAR(MAX),
    [ID Cuộn Bó] FLOAT PRIMARY KEY,
    [Vị trí] NVARCHAR(MAX),
    [Khối lượng] FLOAT,
    [Nhóm] NVARCHAR(MAX),
    [Ca] NVARCHAR(MAX),
    [Ngày sản xuất] NVARCHAR(MAX),
    [SO Mapping] FLOAT,
    [SO Item Ma] FLOAT,
    [Customer N] NVARCHAR(MAX),
    [Batch] FLOAT,
    [Order] FLOAT,
    [Loại thép] NVARCHAR(MAX),
    [Chiều dài] FLOAT,
    [Đường kính] FLOAT,
    [Mác thép] NVARCHAR(MAX),
    [Tiêu chuẩn] NVARCHAR(MAX),
    [Đơn vị tính] NVARCHAR(MAX),
    [Số lượng] FLOAT,
    [Lô Phôi] NVARCHAR(MAX),
    [Phân xưởng] FLOAT,
    [Nhà máy] FLOAT,
    [Trạm cân] FLOAT,
    [Cơ lý] FLOAT,
    [Số lượng in] FLOAT,
    [Nhập tay] NVARCHAR(MAX),
    [SampleID] FLOAT,
    [Customer M] FLOAT,
    [Tp loại 2] NVARCHAR(MAX),
    [snapshot_ts] NVARCHAR(MAX),
    [status] NVARCHAR(MAX)
);

CREATE TABLE dbo.kho_removed (
    [Plant] FLOAT,
    [Material] FLOAT,
    [Storage Location] FLOAT,
    [Material Description] NVARCHAR(MAX),
    [ID Cuộn Bó] FLOAT,
    [Vị trí] NVARCHAR(MAX),
    [Khối lượng] FLOAT,
    [Nhóm] NVARCHAR(MAX),
    [Ca] NVARCHAR(MAX),
    [Ngày sản xuất] NVARCHAR(MAX),
    [SO Mapping] FLOAT,
    [SO Item Ma] FLOAT,
    [Customer N] NVARCHAR(MAX),
    [Batch] FLOAT,
    [Order] FLOAT,
    [Loại thép] NVARCHAR(MAX),
    [Chiều dài] FLOAT,
    [Đường kính] FLOAT,
    [Mác thép] NVARCHAR(MAX),
    [Tiêu chuẩn] NVARCHAR(MAX),
    [Đơn vị tính] NVARCHAR(MAX),
    [Số lượng] FLOAT,
    [Lô Phôi] NVARCHAR(MAX),
    [Phân xưởng] FLOAT,
    [Nhà máy] FLOAT,
    [Trạm cân] FLOAT,
    [Cơ lý] FLOAT,
    [Số lượng in] FLOAT,
    [Nhập tay] NVARCHAR(MAX),
    [SampleID] FLOAT,
    [Customer M] FLOAT,
    [Tp loại 2] NVARCHAR(MAX),
    [snapshot_ts] NVARCHAR(MAX),
    [status] NVARCHAR(MAX)
);

CREATE TABLE dbo.lichtau (
    [STT] FLOAT,
    [SỐ LỆNH TÁCH] NVARCHAR(MAX),
    [TÀU/PHƯƠNG TIỆN VẬN TẢI] NVARCHAR(MAX),
    [KHỐI LƯỢNG TỔNG TÀU] FLOAT,
    [ETA DUNG QUẤT] NVARCHAR(MAX),
    [ĐẠI LÝ] NVARCHAR(MAX),
    [ETB DUNG QUẤT] NVARCHAR(MAX),
    [NGÀY DK DUYỆT SO] NVARCHAR(MAX),
    [Cảng xếp] NVARCHAR(MAX),
    [CẢNG ĐẾN] NVARCHAR(MAX),
    [LỆNH XUẤT HÀNG - KẾ HOẠCH DUYỆT (SỐ LỆNH ĐẦY ĐỦ - SỐ XNĐH - KL TỔNG ĐƠN - LSD) (MỖI LỆNH 1 DÒNG)] NVARCHAR(MAX),
    [KHỐI LƯỢNG HÀNG XUẤT LÊN TÀU] FLOAT,
    [SẢN XUẤT (HRC 1/2-TÌNH TRẠNG)] NVARCHAR(MAX),
    [C.W MAX TÀU NHẬN ĐƯỢC] FLOAT,
    [GHI CHÚ] NVARCHAR(MAX),
    [NHỊP] INT,
    [TÌNH TRẠNG] FLOAT,
    [SO] FLOAT,
    [TỔNG ĐÃ MAP] FLOAT,
    [ĐÃ XUẤT] NVARCHAR(MAX),
    [CÒN LẠI] NVARCHAR(MAX)
);

CREATE TABLE [lsx] (
    [Order] BIGINT,
    [KHÁCH HÀNG] NVARCHAR(MAX),
    [Ngày bắt đầu block] DATETIME,
    [Ngày kết thúc block] DATETIME,
    [Sản lượng 1A] INT,
    [Sản lượng 1B] INT,
    [Tổng yêu cầu] FLOAT,
    [SL trung bình/ngày] FLOAT,
    [Mac thep] NVARCHAR(50),
    [Yêu cầu đặc biệt] NVARCHAR(MAX),
    [Số_lô_Batch] BIGINT,
    [KL_Cuộn_(Tấn)] NVARCHAR(MAX),
    [Mục đích sử dụng] NVARCHAR(MAX),
    [Khối lượng cuộn trung bình] FLOAT,
    [lsx_id] NVARCHAR(MAX)
)

CREATE TABLE dbo.report (
    [Order] FLOAT,
    [KHÁCH HÀNG] NVARCHAR(MAX),
    [Tổng yêu cầu] FLOAT,
    [SL trung bình/ngày] FLOAT,
    [lsx_id] NVARCHAR(MAX),
    [Ngày] DATETIME,
    [Sản lượng thực tế] FLOAT,
    [Tổng sản lượng thực tế] FLOAT,
    [Trong_khoang_LSX] INT,
    [Trạng thái] NVARCHAR(MAX)
);

CREATE TABLE dbo.sanluong (
    [Material Description] NVARCHAR(MAX),
    [Nhóm] NVARCHAR(MAX),
    [ID Cuộn Bó] FLOAT,
    [Khối lượng] FLOAT,
    [Vị trí] NVARCHAR(MAX),
    [Lô Phôi XK] NVARCHAR(MAX),
    [Ngày sản xuất] NVARCHAR(MAX),
    [Batch] FLOAT,
    [ID Ref] FLOAT,
    [Order] FLOAT,
    [Tp loại 2] INT,
    [QLCL] INT,
    [Material] FLOAT,
    [Ca] NVARCHAR(MAX),
    [Đã xóa] NVARCHAR(MAX),
    [Đã nhập kho] NVARCHAR(MAX),
    [Lô phôi] NVARCHAR(MAX),
    [Đường kính] FLOAT,
    [Mác thép] NVARCHAR(MAX),
    [Đã chuyển] NVARCHAR(MAX),
    [Đã xuất kho] NVARCHAR(MAX),
    [Chuyển loại] NVARCHAR(MAX),
    [Lỗi đơn trọng dương - L*(+)] INT,
    [Đã chuyển kho bán hàng] NVARCHAR(MAX),
	NhaMay NVARCHAR(100),
	snapshot_ts NVARCHAR(MAX),
	status NVARCHAR(MAX
);

CREATE TABLE dbo.sanluongthucte (
    [Order] FLOAT,
    [Ngày] DATETIME,
    [Sản lượng thực tế] FLOAT
);

CREATE TABLE dbo.sanluongthuctetong (
    [Order] FLOAT,
    [Tổng sản lượng thực tế] FLOAT
);

CREATE TABLE dbo.so (
    [PO.] NVARCHAR(MAX),
    [Sales Document] BIGINT,
    [Customer] NVARCHAR(MAX),
    [Material] BIGINT,
    [Item Description] NVARCHAR(MAX),
    [Quantity (KG)] FLOAT,
    [Quantity (S.U)] FLOAT,
    [Deli.Priority] BIGINT,
    [Shipped Quantity (S.U)] FLOAT,
    [Shipped Quantity (KG)] FLOAT,
    [Delivery Status Description] NVARCHAR(MAX),
    [Cus.PO.] FLOAT,
    [Factory] NVARCHAR(MAX),
    [Ship to party] NVARCHAR(MAX),
    [Customer Number] BIGINT,
    [Billed Qty] FLOAT,
    [Billed Qty (KG)] FLOAT,
    [Created by] NVARCHAR(MAX),
    [Sales Unit] NVARCHAR(MAX),
    [Sales Document Item] BIGINT,
    [Schedule Delivery Date] FLOAT,
    [Basic data text] NVARCHAR(MAX),
    [Reqd Deliv Date] NVARCHAR(MAX),
    [SL cần xuất] FLOAT,
    [Ghi chú GH (LXH)] FLOAT,
    [Ghi chu (YCSX)] FLOAT,
    [Batch] FLOAT,
    [Size] NVARCHAR(MAX),
    [Status] NVARCHAR(MAX),
    [snapshot_ts] NVARCHAR(MAX),
    [status1] NVARCHAR(MAX),
    CONSTRAINT PK_so PRIMARY KEY ([Sales Document],[Material],[Sales Document Item])
);

CREATE TABLE dbo.so_removed (
    [PO.] NVARCHAR(MAX),
    [Sales Document] BIGINT,
    [Customer] NVARCHAR(MAX),
    [Material] BIGINT,
    [Item Description] NVARCHAR(MAX),
    [Quantity (KG)] FLOAT,
    [Quantity (S.U)] FLOAT,
    [Deli.Priority] BIGINT,
    [Shipped Quantity (S.U)] FLOAT,
    [Shipped Quantity (KG)] FLOAT,
    [Delivery Status Description] NVARCHAR(MAX),
    [Cus.PO.] FLOAT,
    [Factory] NVARCHAR(MAX),
    [Ship to party] NVARCHAR(MAX),
    [Customer Number] BIGINT,
    [Billed Qty] FLOAT,
    [Billed Qty (KG)] FLOAT,
    [Created by] NVARCHAR(MAX),
    [Sales Unit] NVARCHAR(MAX),
    [Sales Document Item] BIGINT,
    [Schedule Delivery Date] FLOAT,
    [Basic data text] NVARCHAR(MAX),
    [Reqd Deliv Date] NVARCHAR(MAX),
    [SL cần xuất] FLOAT,
    [Ghi chú GH (LXH)] FLOAT,
    [Ghi chu (YCSX)] FLOAT,
    [Batch] FLOAT,
    [Size] NVARCHAR(MAX),
    [Status] NVARCHAR(MAX),
    [snapshot_ts] NVARCHAR(MAX),
    [status1] NVARCHAR(MAX),
    CONSTRAINT PK_so PRIMARY KEY ([Sales Document],[Material],[Sales Document Item])
);

CREATE TABLE dbo.ton_kho (
    [index] FLOAT,
    [Order] BIGINT,
    [Material] NVARCHAR(MAX),
    [Material Description_x] NVARCHAR(MAX),
    [Tồn kho chưa Mapping SO] INT,
    [Tồn kho Mapping SO] INT,
    [Tổng tồn kho] INT,
    [Tổng Loại 1] INT,
    [Tổng Loại 2] INT,
    [Số lượng chờ nhập kho] INT,
    [SO Mapping] BIGINT,
    [Material Description_y] NVARCHAR(MAX),
    [Customer N] NVARCHAR(MAX),
    [SL Mapping kho] INT,
    [Shipped Quantity (KG)] INT,
    [Quantity (KG)] INT,
    [Process] INT,
    [Material Description] NVARCHAR(MAX),
    [lsx_id] NVARCHAR(MAX)
);
GO
